#pragma once
#include<SDL2/SDL.h>
#include<SDL2/SDL_image.h>
#include<SDL2/SDL_mixer.h>

#define SCREEN_WIDTH 1280
#define SCREEN_HEIGHT 960

#define NEW_WIDTH(x) (((x) * (SCREEN_WIDTH))/540)
#define NEW_HEIGHT(x) (((x) * (SCREEN_HEIGHT))/720)

#define CHANGE_WIDTH(x) (((x) * (SCREEN_WIDTH))/1280)
#define CHANGE_HEIGHT(x) (((x) * (SCREEN_HEIGHT))/960)

#define CAR_WIDTH  NEW_WIDTH(100)
#define CAR_HEIGHT NEW_HEIGHT(40)

#define SCOPE_SPEED CHANGE_WIDTH(25)
#define JUNGLEE1_SPEED CHANGE_WIDTH(19)
#define JUNGLEE2_SPEED CHANGE_WIDTH(21)
#define JUNGLEE3_SPEED CHANGE_WIDTH(15)
#define JUNGLEE4_SPEED CHANGE_WIDTH(17)
#define JUNGLEE5_SPEED CHANGE_WIDTH(23)

#define DEFAULT_x  NEW_WIDTH(250)
#define DEFAULT_y NEW_HEIGHT(650)

#define MAZE_x NEW_WIDTH(390)
#define MAZE_y NEW_HEIGHT(175)

#define PLAYER_SPEED CHANGE_WIDTH(7)
#define MAZE_SPEED CHANGE_WIDTH(8)
#define PLAYER_WIDTH NEW_WIDTH(22)
#define PLAYER_HEIGHT NEW_HEIGHT(45)

#define CAR0_SPEED CHANGE_WIDTH(30)
#define CAR1_SPEED CHANGE_WIDTH(25)
#define CAR2_SPEED CHANGE_WIDTH(31)
#define CAR3_SPEED CHANGE_WIDTH(34)
#define CAR4_SPEED CHANGE_WIDTH(24)

#define MAX_KEYBOARD_KEYS 350
#define MAX_MOUSE_BUTTONS 5
#define MAX_LEVELS 5

#define MAX_SND_CHANNELS 8
